### ISSUE TITLE
not accessible from toolbar

### ISSUE THREAD

**Issue by ghost** [ShaneKilkelly/firefox-plus-bookmarks#1]
fennec 52.0.2
android 5.1

the addon is not accessible from toolbar.
there are no options in +bookmarks addon.

**Comment by JuneKelly** [comment]
As I don't have access to an Android device currently, this isn't likely to be fixed.

Pull Requests welcome though, if anyone figures out a fix.

Thanks!

**Comment by ghost** [comment]
please excuse i have written another review. 

please see comment 2 https://bugzilla.mozilla.org/show_bug.cgi?id=1367717

**Comment by JuneKelly** [comment]
Thanks for highlighting this issue, I didn't realize I'd checked the "Android" box when uploading the release.

It's fixed now, the extension no longer claims to be compatible with android.
